version: '3.8'

services:
  web:
    build: .
    container_name: flask_app_container
    restart: always
    environment:
      - SECRET_KEY=chave_secreta_producao_docker
    expose:
      - "5000"

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy_container
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web